import { PunchlyWordmark } from "@/components/brand/logo";
import { FileCheck, CheckCircle, Calendar, Building2 } from "lucide-react";

export default function ReportPage({ params }: { params: { id: string } }) {
  // Parse the report ID to extract info
  const reportParts = params.id.split('_');
  const projectName = reportParts[0]?.replace(/-/g, ' ') || 'Project';
  const unitNumber = reportParts[1] || 'Unit';

  return (
    <div className="min-h-screen bg-white flex items-center justify-center px-4 py-12">
      <div className="max-w-3xl w-full">
        <div className="text-center mb-8">
          <PunchlyWordmark />
        </div>

        <div className="bg-white border-2 border-zinc-800 rounded-xl shadow-2xl overflow-hidden">
          {/* Header Section */}
          <div className="bg-zinc-900 text-white p-8 text-center">
            <div className="inline-flex items-center justify-center h-16 w-16 rounded-full bg-green-500 mb-4">
              <CheckCircle className="h-8 w-8 text-white" />
            </div>
            <h1 className="text-3xl font-bold mb-2">
              Verified Inspection Report
            </h1>
            <p className="text-zinc-300 text-sm">
              This QR code confirms the authenticity of your snag inspection
            </p>
          </div>

          {/* Report Details */}
          <div className="p-8">
            <div className="bg-zinc-50 border-2 border-zinc-200 rounded-lg p-6 mb-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="flex items-start gap-3">
                  <Building2 className="h-5 w-5 text-zinc-600 mt-0.5" />
                  <div>
                    <p className="text-xs font-semibold text-zinc-500 uppercase">Project</p>
                    <p className="text-base font-bold text-zinc-900">{projectName}</p>
                  </div>
                </div>
                <div className="flex items-start gap-3">
                  <FileCheck className="h-5 w-5 text-zinc-600 mt-0.5" />
                  <div>
                    <p className="text-xs font-semibold text-zinc-500 uppercase">Unit</p>
                    <p className="text-base font-bold text-zinc-900">{unitNumber}</p>
                  </div>
                </div>
              </div>

              <div className="mt-4 pt-4 border-t border-zinc-200">
                <p className="text-xs text-zinc-500 font-mono">
                  Report ID: {params.id}
                </p>
              </div>
            </div>

            {/* Information Section */}
            <div className="space-y-4 mb-6">
              <div className="flex items-start gap-3 p-4 bg-blue-50 border border-blue-200 rounded-lg">
                <div className="h-2 w-2 rounded-full bg-blue-500 mt-2"></div>
                <div>
                  <h3 className="font-semibold text-zinc-900 mb-1">PDF Report Delivered</h3>
                  <p className="text-sm text-zinc-700">
                    The complete PDF inspection report with photos and detailed snag descriptions was delivered to the site inspector.
                  </p>
                </div>
              </div>

              <div className="flex items-start gap-3 p-4 bg-green-50 border border-green-200 rounded-lg">
                <div className="h-2 w-2 rounded-full bg-green-500 mt-2"></div>
                <div>
                  <h3 className="font-semibold text-zinc-900 mb-1">Authenticity Verified</h3>
                  <p className="text-sm text-zinc-700">
                    This QR code serves as digital verification that this report was generated by Punchly's official platform.
                  </p>
                </div>
              </div>

              <div className="flex items-start gap-3 p-4 bg-purple-50 border border-purple-200 rounded-lg">
                <div className="h-2 w-2 rounded-full bg-purple-500 mt-2"></div>
                <div>
                  <h3 className="font-semibold text-zinc-900 mb-1">Digital Archive</h3>
                  <p className="text-sm text-zinc-700">
                    All inspection data is securely stored in Punchly's digital archive for future reference and tracking.
                  </p>
                </div>
              </div>
            </div>

            {/* Footer */}
            <div className="pt-6 border-t border-zinc-200 text-center">
              <p className="text-xs text-zinc-500 mb-2">
                Powered by Punchly - Enterprise Digital Snagging Platform
              </p>
              <a
                href="/"
                className="text-sm text-zinc-900 font-semibold hover:underline"
              >
                Visit Punchly →
              </a>
            </div>
          </div>
        </div>

        <div className="mt-6 text-center">
          <a
            href="/"
            className="text-sm text-zinc-600 hover:text-zinc-900 transition-colors inline-flex items-center gap-2"
          >
            ← Back to Platform
          </a>
        </div>
      </div>
    </div>
  );
}
