import { PunchlyWordmark } from "@/components/brand/logo";
import { FileCheck } from "lucide-react";

export default function ReportPage({ params }: { params: { id: string } }) {
  return (
    <div className="min-h-screen bg-white flex items-center justify-center px-4">
      <div className="max-w-2xl w-full">
        <div className="text-center mb-8">
          <PunchlyWordmark />
        </div>

        <div className="bg-white border-2 border-zinc-800 rounded-xl p-12 shadow-lg">
          <div className="flex flex-col items-center text-center">
            <div className="h-20 w-20 rounded-full bg-green-100 flex items-center justify-center mb-6">
              <FileCheck className="h-10 w-10 text-green-600" />
            </div>

            <h1 className="text-3xl font-bold text-zinc-900 mb-4">
              Digital Report Access
            </h1>

            <p className="text-lg text-zinc-600 mb-6">
              Report ID: <span className="font-mono font-semibold">{params.id}</span>
            </p>

            <div className="bg-zinc-50 border-2 border-zinc-200 rounded-lg p-6 w-full max-w-md">
              <p className="text-sm text-zinc-700 mb-4">
                This is a digital snag report generated by Punchly.
              </p>
              <p className="text-sm text-zinc-600">
                The PDF version contains all inspection details, photos, and snag locations.
              </p>
            </div>

            <div className="mt-8 pt-8 border-t border-zinc-200 w-full">
              <p className="text-xs text-zinc-500">
                Powered by Punchly - Digital Snagging Platform
              </p>
              <p className="text-xs text-zinc-500 mt-2">
                For more information, visit{" "}
                <a href="/" className="text-zinc-900 underline hover:text-zinc-700">
                  Punchly
                </a>
              </p>
            </div>
          </div>
        </div>

        <div className="mt-6 text-center">
          <a
            href="/"
            className="text-sm text-zinc-600 hover:text-zinc-900 transition-colors"
          >
            ← Back to Home
          </a>
        </div>
      </div>
    </div>
  );
}
